sax = require('sax')

strict = true
options = {}

# stream usage
# takes the same options as the parser
saxStream = sax.createStream(strict, options)
saxStream.on 'error', (e) ->
  return
saxStream.on 'opentag', (node) ->
  # same object as above
  return
# pipe is supported, and it's readable/writable
# same chunks coming in also go out.
# fs.createReadStream('file.xml').pipe(saxStream).pipe fs.createWriteStream('file-copy.xml')

# ---
# generated by js2coffee 2.0.1

